<?php
return [
    // start answer qustion 2
    [
        'survey_answer_id'=>1,
        'survey_answer_question_id'=>2,
        'survey_answer_name'=>'Q2 One choice',
        'survey_answer_descr'=>'Q2 One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>2,
        'survey_answer_question_id'=>2,
        'survey_answer_name'=>'Q2 Two choice',
        'survey_answer_descr'=>'Q2 Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>3,
        'survey_answer_question_id'=>2,
        'survey_answer_name'=>'Q2 Three choice',
        'survey_answer_descr'=>'Q2 Three desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Three choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ], // end answer question 2

    // start answer question 3
    [
        'survey_answer_id'=>4,
        'survey_answer_question_id'=>3,
        'survey_answer_name'=>'Q3 One choice',
        'survey_answer_descr'=>'Q3 One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>5,
        'survey_answer_question_id'=>3,
        'survey_answer_name'=>'Q3 Two choice',
        'survey_answer_descr'=>'Q3 Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>6,
        'survey_answer_question_id'=>3,
        'survey_answer_name'=>'Q3 Three choice',
        'survey_answer_descr'=>'Q3 Three desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Three choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ], // end answer question 3

    // start answer question 4
    [
        'survey_answer_id'=>7,
        'survey_answer_question_id'=>4,
        'survey_answer_name'=>'Q4 One choice',
        'survey_answer_descr'=>'Q4 One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>8,
        'survey_answer_question_id'=>4,
        'survey_answer_name'=>'Q4 Two choice',
        'survey_answer_descr'=>'Q4 Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>9,
        'survey_answer_question_id'=>4,
        'survey_answer_name'=>'Q4 Three choice',
        'survey_answer_descr'=>'Q4 Three desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Three choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ], // end answer question 4
    // start answer question 5
    [
        'survey_answer_id'=>10,
        'survey_answer_question_id'=>5,
        'survey_answer_name'=>'Q5 One choice',
        'survey_answer_descr'=>'Q5 One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>11,
        'survey_answer_question_id'=>5,
        'survey_answer_name'=>'Q5 Two choice',
        'survey_answer_descr'=>'Q5 Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>12,
        'survey_answer_question_id'=>5,
        'survey_answer_name'=>'Q5 Three choice',
        'survey_answer_descr'=>'Q5 Three desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Three choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>13,
        'survey_answer_question_id'=>5,
        'survey_answer_name'=>'Q5 Four choice',
        'survey_answer_descr'=>'Q5 Four desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Four choice corrective',
        'correct'=>1,
        'corrective_action_date'=>null,
    ], // end answer question 5
    // start answer question 6
    [
        'survey_answer_id'=>14,
        'survey_answer_question_id'=>6,
        'survey_answer_name'=>0,
        'survey_answer_descr'=>'Q6 One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>15,
        'survey_answer_question_id'=>6,
        'survey_answer_name'=>100,
        'survey_answer_descr'=>'Q6 Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ], // end answer question 6
    // start answer question 8
    [
        'survey_answer_id'=>16,
        'survey_answer_question_id'=>8,
        'survey_answer_name'=>'2019-11-01',
        'survey_answer_descr'=>'Q8 One desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'One choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ],
    [
        'survey_answer_id'=>17,
        'survey_answer_question_id'=>8,
        'survey_answer_name'=>'2019-11-29',
        'survey_answer_descr'=>'Q8 Two desc',
        'survey_answer_points'=>0,
        'survey_answer_show_descr'=>0,
        'survey_answer_show_corrective_action'=>0,
        'survey_answer_corrective_action'=>'Two choice corrective',
        'correct'=>0,
        'corrective_action_date'=>null,
    ], // end answer question 8

];
