<?php
return [
    [
        'survey_question_id'=>1,
        'survey_question_name'=> 'Q1',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>6, // text
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>2,
        'survey_question_name'=> 'Q2',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>1, // Multiple choice
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>3,
        'survey_question_name'=> 'Q3',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>2, // One choise of list
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>4,
        'survey_question_name'=> 'Q4',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>3, // Dropdown
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>5,
        'survey_question_name'=> 'Q5',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>4, // Ranking
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>6,
        'survey_question_name'=> 'Q6',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>5, // Rating
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>5,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>7,
        'survey_question_name'=> 'Q7',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>8, // Comment box
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>8,
        'survey_question_name'=> 'Q8',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>9, // Date/Time
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
    [
        'survey_question_id'=>9,
        'survey_question_name'=> 'Q9',
        'survey_question_descr'=>'Desc',
        'survey_question_type'=>11, // File
        'survey_question_survey_id'=>1,
        'survey_question_can_skip'=>0,
        'survey_question_show_descr'=>0,
        'survey_question_attachment_file'=>0,
        'steps'=>0,
        'survey_question_point'=>5,
    ],
];
